### ISSUE TITLE
Failed to obtain Auth token

### ISSUE THREAD

**Issue by underchemist** [sparkgeo/prescient-sdk#24]
Worked as of 2024-11-05, however now getting an `invalid_client` error without changing contents of config.env or updating packages as far as I can tell.

config.env contents:

```
PRESCIENT_ENDPOINT_URL=<PRESCIENT_UAT_URL>
PRESCIENT_AWS_REGION="us-west-2"
PRESCIENT_AWS_ROLE=<AWS_ROLE_ARN>
PRESCIENT_TENANT_ID=<TENANT_ID>
PRESCIENT_CLIENT_ID=<CLIENT_ID
PRESCIENT_AUTH_URL="https://login.microsoft.com"
PRESCIENT_AUTH_TOKEN_PATH="/oauth2/v2.0/token"
```

Reproducible example:

```python
from prescient_sdk.client import PrescientClient

client = PrescientClient()
client.auth_credentials
Traceback (most recent call last):
  File "/home/ysebastien/git/enexus-raster-math/main.py", line 97, in <module>
    client.auth_credentials
  File "/home/ysebastien/git/enexus-raster-math/.venv/lib/python3.12/site-packages/prescient_sdk/client.py", line 157, in auth_credentials
    raise ValueError(f"Failed to obtain Auth token: {self._auth_credentials}")
ValueError: Failed to obtain Auth token: {'error': 'invalid_client', 'error_description': "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: e0300674-91f1-4d54-b4a7-9682e0213900 Correlation ID: 403d5ba8-7755-48a3-80f6-fe86dfbd3bbc Timestamp: 2024-11-06 19:42:37Z", 'error_codes': [7000218], 'timestamp': '2024-11-06 19:42:37Z', 'trace_id': 'e0300674-91f1-4d54-b4a7-9682e0213900', 'correlation_id': '403d5ba8-7755-48a3-80f6-fe86dfbd3bbc', 'error_uri': 'https://login.microsoft.com/error?code=7000218'}
```

**Comment by underchemist** [comment]
Looks like client ID has expired in Azure

**Comment by michaelconnor00** [comment]
The auth flow we are using does not require a client_secret. This is likely an azure configuration change. Likely something I changed when trying to help David with the UI.

**Comment by michaelconnor00** [comment]
I re-enabled the `allow public client flows`, which is a setting I was testing when Enbridge was having problems.
